name: app_booking_seat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  fonts:
    - family: DB Heavent
      fonts:
        - asset: lib/assets/font/DB Heavent Bd It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Bd v3.2.ttf
        - asset: lib/assets/font/DB Heavent Blk It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Blk v3.2.ttf
        - asset: lib/assets/font/DB Heavent It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Li It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Li v3.2.ttf
        - asset: lib/assets/font/DB Heavent Med v3.2.ttf
        - asset: lib/assets/font/DB Heavent Thin It v3.2.ttf
        - asset: lib/assets/font/DB Heavent Thin v3.2.ttf
        - asset: lib/assets/font/DB Heavent UlLi It v3.2.ttf
        - asset: lib/assets/font/DB Heavent UlLi v3.2.ttf
        - asset: lib/assets/font/DB Heavent v3.2.ttf
